---
title: "FAQ"
output: html_document
---

```{r, echo=FALSE}

```

### Quick Answers:

Let's get started!

- Do you see your question? If not, please contack nuo@uw.edu via email for additional help.
- This application is meant to be a primary search tool for students to have a general idea of the Universities, for more detailed admission requirements and the most recent statistics please check their official site. 
- The SAT scores in this dataset is not applicable for the old version of SAT (Out of 2400). Checkout the score conversion chart [here](http://magoosh.com/hs/act/act-scores/2016/act-to-new-sat-to-old-sat-score-conversion-chart/)!





##### 1. What's the difference between SAT and ACT?

> While both SAT and ACT are standardized tests recognized by most colleges in the United States. There are some differences between them regarding the test materials. In addition, the ACT is scored on a scale of 1-36 and the SAT is scored on a scale of 400-1600.

##### 2. Which one should I take, SAT or ACT?

> Students may take whichever test they prefer (assuming there are available testing locations for both tests). If you're not sure which test your child would prefer, consider the key differences between the ACT and SAT. Some students find that the ACT caters to their strengths more so than the SAT, and vice versa. Overall, the ACT questions tend to be more straight forward and the writing section of SAT has a stronger emphasis on vocabulary. Although the essay section for both tests are optional, the SAT essay is more comprehension focused while the ACT wants to see how well you can evaluate and take a position on complex issues. 

##### 3. My score is lower than the average score of the school, do I still have a chance?

> Yes, absolutely. While you grades and test scores have a considerable impact on your admission decision, most of the College admission committees conduct the Holistic review process that takes into account your extracurricular activities, community involvments as well as your other talents.

##### 4. Am I guaranteed to get in the school if I have a high score?

> Not really, again while grades and test scores have a considerable impact on your admission decision, the admission committee of the College are looking for students who are the right fit for their school. The best thing you can do is to demonstrate all apsects of you in the application.

##### 5. I cannot find the test score statistics of my school, what should do?

> The dataset used for this project is retrieved from data.gov, however, some colleges may have yet to complete their admission statistics. We will try our best to complete the dataset and in the mean time, please checkout their official website for more detailed information. 


